dataset:
  _target_: sunscc.dataset.SunSCCDataModule
  data_dir: "/globalscratch/users/n/s/nsayez/Classification_dataset"
  dataset_name: "2002-2019"
  batch_size: 16
  num_workers: 12

  train_dataset:
    _target_: sunscc.dataset.DeepsunSegmentationDataset
    partition: "input"
    dtypes: ${use_dtypes}

    transforms:
      - _target_: sunscc.transforms.DeepsunRandomFlip
      - _target_: sunscc.transforms.DeepsunRandomRotate
      - _target_: sunscc.transforms.DeepsunCropNonEmptyMaskIfExists
        height: 512
        width: 512
      - _target_: sunscc.transforms.DeepsunRandomMaskSelector
        

  val_dataset:
    _target_: sunscc.dataset.DeepsunSegmentationDataset
    partition: "input"
    dtypes: ${use_dtypes}
    transforms:
      - _target_: sunscc.transforms.DeepsunRandomFlip
      - _target_: sunscc.transforms.DeepsunRandomRotate
      - _target_: sunscc.transforms.DeepsunCropNonEmptyMaskIfExists
        height: 512
        width: 512
      - _target_: sunscc.transforms.DeepsunMaskMerger
        p_add: 0.5

  test_dataset:     
    _target_: sunscc.dataset.DeepsunSegmentationTestDataset
    partition: "input"
    dtypes: ['image']
    transforms:
      - _target_: sunscc.transforms.DeepsunRandomFlip
      - _target_: sunscc.transforms.DeepsunRandomRotate
      - _target_: sunscc.transforms.DeepsunCropNonEmptyMaskIfExists
        height: 512
        width: 512


