_target_: sunscc.model.McIntoshClassifier_MobilenetEncoder

input_format: 
    visual: ["image", "mask","mask_one_hot", "mask_LargestSpot", "group_mask", "group_mask_LargestSpot"]
    numeric: [ "angular_excentricity", "centroid_Lat" ]



# output_format: ["McIntosh1","McIntosh2","McIntosh3"]
output_format: ["class1","class2","class3"]
# output_format: ["Superclass"]

classes: ${use_classes}
first_classes: ${first_classes}
second_classes: ${second_classes}
third_classes: ${third_classes}

cascade: true
double_encoder: false

num_channels_offset: 0

architecture:
  mobilenet_version: 'v2'
  pretrained: true
  MLP1: [512,256,256,128]
  MLP2: [512,256,256,128]
  MLP3: [512,256,256,128]

focus_on_group: ${focus_on_group}
focus_on_largest_sunspot: ${focus_on_largest_sunspot}
