defaults:
  - _self_
  - trainer: default
  - model: conf_unet
  - module: base_segmentation
  - dataset: deepsun
  - logger: "none"
  - server: "local"
  - exp: test
  # - override hydra/launcher: gpu

seed: 0
hydra:
  job:
    env_set:
      DATA_DIR: "${oc.env:HOME}/projects/sunscc/data"
